// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Language from "./Language.bs.js";
import * as ReactIntl from "react-intl";
import * as Translation from "./Translation.bs.js";

function IntlProvider(Props) {
  var children = Props.children;
  var match = React.useState(function () {
        return /* Cs */0;
      });
  var defaultLanguage = match[0];
  return React.createElement(ReactIntl.IntlProvider, {
              locale: Language.toString(defaultLanguage),
              messages: Translation.getTranslation(defaultLanguage),
              defaultLocale: Language.toString(defaultLanguage),
              children: children
            });
}

var make = IntlProvider;

export {
  make ,
}
/* react Not a pure module */
