// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Language from "./Language.bs.js";
import * as ReactIntl from "react-intl";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Translation from "./Translation.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function IntlProvider(props) {
  var match = React.useState(function () {
        return /* Cs */0;
      });
  var defaultLanguage = match[0];
  return JsxRuntime.jsx(ReactIntl.IntlProvider, {
              locale: Language.toString(defaultLanguage),
              messages: Caml_option.some(Translation.getTranslation(defaultLanguage)),
              defaultLocale: Language.toString(defaultLanguage),
              children: props.children
            });
}

var make = IntlProvider;

export {
  make ,
}
/* react Not a pure module */
