// Generated by ReScript, PLEASE EDIT WITH CARE


function fromString(languageCode) {
  switch (languageCode) {
    case "cs" :
    case "cs-CZ" :
    case "cs_CZ" :
        return /* Cs */0;
    default:
      return ;
  }
}

function toString(language) {
  return "cs";
}

export {
  fromString ,
  toString ,
}
/* No side effect */
