// Generated by ReScript, PLEASE EDIT WITH CARE


var Menu_aboutUs = {
  id: "0371f3b2-5b62-4c6b-baac-a3925b811458",
  defaultMessage: "O nás"
};

var Menu_registrations = {
  id: "b54fd38e-5cab-4dc6-9db0-c3f2bc180395",
  defaultMessage: "Registrace"
};

var Menu_references = {
  id: "6bf7df3e-31ef-4204-863a-9cf963d73779",
  defaultMessage: "Reference"
};

var Menu_contact = {
  id: "6bf7df3e-31ef-4204-863a-9cf963d73779",
  defaultMessage: "Kontakt"
};

var Menu = {
  aboutUs: Menu_aboutUs,
  registrations: Menu_registrations,
  references: Menu_references,
  contact: Menu_contact
};

var AboutUs_header = {
  id: "cb394fa9-9b9e-4b10-8d3e-7c78a1e75dc7",
  defaultMessage: "Casting dětí - POPPY CASTING - castingová agentura"
};

var AboutUs_paragraph1 = {
  id: "9c048db6-f90d-48da-a31e-06187c783a60",
  defaultMessage: "Agenturu Poppy Casting založila herečka, produkční a dabingová režisérka Martina Popperová, která se od roku 2003 herecky podílela například na těchto projektech: Sametoví vrazi, Strážce duší, Ulice, To horké léto v Marienbadu, Žil jsem s cizinkou, Láska v Praze, Trapasy, Hop nebo Trop, Nepolepšitelný, Vyprávěj, Zdivočelá země, Seznam.cz...a další. Hrála v několika divadlech, jak v České republice tak i na Slovensku. Realizovala nahrávání mnoha mluvených TV a rádio spotů, jak herecky tak i režijně a produkčně."
};

var AboutUs_paragraph2 = {
  id: "91953b1a-c603-4b24-b821-ad620b073b48",
  defaultMessage: "Od roku 2005 pracovala ve společnosti Baby Casting jako hlavní produkční a castingová manažerka, kde se věnovala práci s dětmi a získala bohaté zkušenosti v daném oboru."
};

var AboutUs_paragraph3 = {
  id: "6f71e6a6-a34a-4a73-9806-bac49a58092b",
  defaultMessage: "Agentura Poppy casting je určena dětem od 6 měsíců do 15 let. Spolupracujeme s mnohými agenturami, produkcemi, televizemi a dabingovými studii při obsazování dětských rolí do filmů, seriálů, točených i focených reklam a dabingových spotů. Naším cílem je objevit talentované a zajímavé děti a poskytnout jim příležitost uplatnit se ve filmovém či reklamním prostředí."
};

var AboutUs_paragraph4 = {
  id: "08d300a0-aa59-4a78-8de1-00dd40ae6ce7",
  defaultMessage: "Součástí této práce je také vzdělávání dětí formou herecké přípravy, naučit je jak se chovat před kamerou tak, aby je to bavilo a cítily se přirozeně. Každoročně pořádáme Letní filmový tábor Filmák, nebo různé dabingové a herecké workshopy. O všech možnostech herecké přípravy budeme informovat na těchto stránkách."
};

var AboutUs = {
  header: AboutUs_header,
  paragraph1: AboutUs_paragraph1,
  paragraph2: AboutUs_paragraph2,
  paragraph3: AboutUs_paragraph3,
  paragraph4: AboutUs_paragraph4
};

var appName = {
  id: "1c7ff9c8-a7f2-40bf-a645-f7ac48cdfbd9",
  defaultMessage: "Poppy Casting"
};

export {
  appName ,
  Menu ,
  AboutUs ,
}
/* No side effect */
