// Generated by ReScript, PLEASE EDIT WITH CARE


var Menu_aboutUs = {
  id: "0371f3b2-5b62-4c6b-baac-a3925b811458",
  defaultMessage: "O nás"
};

var Menu_registrations = {
  id: "b54fd38e-5cab-4dc6-9db0-c3f2bc180395",
  defaultMessage: "Registrace"
};

var Menu_references = {
  id: "6bf7df3e-31ef-4204-863a-9cf963d73779",
  defaultMessage: "Reference"
};

var Menu_contact = {
  id: "6bf7df3e-31ef-4204-863a-9cf963d73779",
  defaultMessage: "Kontakt"
};

var Menu = {
  aboutUs: Menu_aboutUs,
  registrations: Menu_registrations,
  references: Menu_references,
  contact: Menu_contact
};

var appName = {
  id: "1c7ff9c8-a7f2-40bf-a645-f7ac48cdfbd9",
  defaultMessage: "Poppy Casting"
};

export {
  appName ,
  Menu ,
}
/* No side effect */
