// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import MessagesJson from "./_locales/cs/messages.json";

var cs = MessagesJson;

function getTranslation(language) {
  return Js_dict.map((function (param) {
                return param.message;
              }), cs);
}

export {
  cs ,
  getTranslation ,
}
/* cs Not a pure module */
