// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import Close from "@material-ui/icons/Close";

var Close$1 = {};

function Common_Icon_Close(props) {
  return JsxRuntime.jsx(Close, {
              color: props.color,
              fontSize: props.fontSize,
              className: props.className
            });
}

var make = Common_Icon_Close;

export {
  Close$1 as Close,
  make ,
}
/* react/jsx-runtime Not a pure module */
