// Generated by ReScript, PLEASE EDIT WITH CARE


var Menu;

var OpenInNew;

var Close;

var MailOutline;

var KeyboardArrowUp;

export {
  Menu ,
  OpenInNew ,
  Close ,
  MailOutline ,
  KeyboardArrowUp ,
}
/* No side effect */
