// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import OpenInNew from "@material-ui/icons/OpenInNew";

var OpenInNew$1 = {};

function Common_Icon_OpenInNew(Props) {
  var color = Props.color;
  var fontSize = Props.fontSize;
  var className = Props.className;
  var tmp = {};
  if (color !== undefined) {
    tmp.color = color;
  }
  if (fontSize !== undefined) {
    tmp.fontSize = fontSize;
  }
  if (className !== undefined) {
    tmp.className = className;
  }
  return React.createElement(OpenInNew, tmp);
}

var make = Common_Icon_OpenInNew;

export {
  OpenInNew$1 as OpenInNew,
  make ,
}
/* react Not a pure module */
