// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import MailOutline from "@material-ui/icons/MailOutline";

var MailOutline$1 = {};

function Common_Icon_MailOutline(props) {
  return JsxRuntime.jsx(MailOutline, {
              color: props.color,
              fontSize: props.fontSize,
              className: props.className
            });
}

var make = Common_Icon_MailOutline;

export {
  MailOutline$1 as MailOutline,
  make ,
}
/* react/jsx-runtime Not a pure module */
