// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import KeyboardArrowUp from "@material-ui/icons/KeyboardArrowUp";

var KeyboardArrowUp$1 = {};

function Common_Icon_KeyboardArrowUp(props) {
  return JsxRuntime.jsx(KeyboardArrowUp, {
              color: props.color,
              fontSize: props.fontSize,
              className: props.className
            });
}

var make = Common_Icon_KeyboardArrowUp;

export {
  KeyboardArrowUp$1 as KeyboardArrowUp,
  make ,
}
/* react/jsx-runtime Not a pure module */
