// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import MailOutline from "@material-ui/icons/MailOutline";

var MailOutline$1 = {};

function Common_Icon_MailOutline(Props) {
  var color = Props.color;
  var fontSize = Props.fontSize;
  var className = Props.className;
  var tmp = {};
  if (color !== undefined) {
    tmp.color = color;
  }
  if (fontSize !== undefined) {
    tmp.fontSize = fontSize;
  }
  if (className !== undefined) {
    tmp.className = className;
  }
  return React.createElement(MailOutline, tmp);
}

var make = Common_Icon_MailOutline;

export {
  MailOutline$1 as MailOutline,
  make ,
}
/* react Not a pure module */
