// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import KeyboardArrowUp from "@material-ui/icons/KeyboardArrowUp";

var KeyboardArrowUp$1 = {};

function Common_Icon_KeyboardArrowUp(Props) {
  var color = Props.color;
  var fontSize = Props.fontSize;
  var className = Props.className;
  var tmp = {};
  if (color !== undefined) {
    tmp.color = color;
  }
  if (fontSize !== undefined) {
    tmp.fontSize = fontSize;
  }
  if (className !== undefined) {
    tmp.className = className;
  }
  return React.createElement(KeyboardArrowUp, tmp);
}

var make = Common_Icon_KeyboardArrowUp;

export {
  KeyboardArrowUp$1 as KeyboardArrowUp,
  make ,
}
/* react Not a pure module */
