// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import OpenInNew from "@material-ui/icons/OpenInNew";

var OpenInNew$1 = {};

function Common_Icon_OpenInNew(props) {
  return JsxRuntime.jsx(OpenInNew, {
              color: props.color,
              fontSize: props.fontSize,
              className: props.className
            });
}

var make = Common_Icon_OpenInNew;

export {
  OpenInNew$1 as OpenInNew,
  make ,
}
/* react/jsx-runtime Not a pure module */
