// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import Menu from "@material-ui/icons/Menu";

var Menu$1 = {};

function Common_Icon_Menu(props) {
  return JsxRuntime.jsx(Menu, {
              color: props.color,
              fontSize: props.fontSize,
              className: props.className
            });
}

var make = Common_Icon_Menu;

export {
  Menu$1 as Menu,
  make ,
}
/* react/jsx-runtime Not a pure module */
