// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Core$Mui from "rescript-material-ui/src/Core.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import ReactLoadingOverlay from "react-loading-overlay";
import * as Styles from "@material-ui/core/styles";

function Contact_Map(props) {
  var isSmUp = Core.useMediaQuery(Core$Mui.Breakpoint.get(Styles.useTheme(), {
            NAME: "up",
            VAL: "sm"
          }));
  var isMdUp = Core.useMediaQuery(Core$Mui.Breakpoint.get(Styles.useTheme(), {
            NAME: "up",
            VAL: "md"
          }));
  return JsxRuntime.jsx(ReactLoadingOverlay, {
              active: props.isMapBeingLoaded,
              spinner: Caml_option.some(JsxRuntime.jsx(Core.CircularProgress, {})),
              children: Caml_option.some(JsxRuntime.jsx("iframe", {
                        style: {
                          border: "none"
                        },
                        height: isMdUp ? "100%" : (
                            isSmUp ? "333px" : "280px"
                          ),
                        src: props.url,
                        width: "100%",
                        onLoad: props.onMapLoadingFinished
                      })),
              styles: {
                wrapper: Caml_option.some(Js_dict.fromArray([
                          [
                            "position",
                            "relative"
                          ],
                          [
                            "width",
                            "100%"
                          ],
                          [
                            "height",
                            isMdUp ? "100%" : (
                                isSmUp ? "333px" : "280px"
                              )
                          ]
                        ]))
              }
            });
}

var make = Contact_Map;

export {
  make ,
}
/* @material-ui/core Not a pure module */
