// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as App_Context from "../App_Context.bs.js";
import * as Contact_Content from "./Contact_Content.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Contact_Page(props) {
  var match = React.useContext(App_Context.Context.t);
  var dispatch = match[1];
  var activeMenuItem = match[0].activeMenuItem;
  React.useEffect((function () {
          if (activeMenuItem !== /* Contact */4) {
            Curry._1(dispatch, /* StoreActiveMenuItem */{
                  _0: /* Contact */4
                });
          }
          
        }), [activeMenuItem]);
  return JsxRuntime.jsx(Contact_Content.make, {});
}

var make = Contact_Page;

export {
  make ,
}
/* react Not a pure module */
