// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Core$Mui from "rescript-material-ui/src/Core.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import ReactLoadingOverlay from "react-loading-overlay";
import * as Styles from "@material-ui/core/styles";

function Contact_Map(Props) {
  var src = Props.url;
  var active = Props.isMapBeingLoaded;
  var onLoad = Props.onMapLoadingFinished;
  var isSmUp = Core.useMediaQuery(Core$Mui.Breakpoint.get(Styles.useTheme(), {
            NAME: "up",
            VAL: "sm"
          }));
  var isMdUp = Core.useMediaQuery(Core$Mui.Breakpoint.get(Styles.useTheme(), {
            NAME: "up",
            VAL: "md"
          }));
  var tmp = {
    style: {
      border: "none"
    },
    height: isMdUp ? "100%" : (
        isSmUp ? "333px" : "280px"
      ),
    width: "100%",
    onLoad: onLoad
  };
  if (src !== undefined) {
    tmp.src = Caml_option.valFromOption(src);
  }
  return React.createElement(ReactLoadingOverlay, {
              active: active,
              spinner: React.createElement(Core.CircularProgress, {}),
              children: React.createElement("iframe", tmp),
              styles: {
                wrapper: Caml_option.some(Js_dict.fromArray([
                          [
                            "position",
                            "relative"
                          ],
                          [
                            "width",
                            "100%"
                          ],
                          [
                            "height",
                            isMdUp ? "100%" : (
                                isSmUp ? "333px" : "280px"
                              )
                          ]
                        ]))
              }
            });
}

var make = Contact_Map;

export {
  make ,
}
/* react Not a pure module */
