// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";

function Contact_Page(Props) {
  return React.createElement(Core.Grid, {});
}

var make = Contact_Page;

export {
  make ,
}
/* react Not a pure module */
