// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Message from "../i18n/Message.bs.js";
import * as Core$Mui from "rescript-material-ui/src/Core.bs.js";
import * as Grid$Mui from "rescript-material-ui/src/Grid.bs.js";
import * as ReactIntl from "react-intl";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Contact_Map from "./Contact_Map.bs.js";
import * as Common_Style from "../common/Common_Style.bs.js";
import * as Common_Dialog from "../common/Common_Dialog.bs.js";
import * as Common_Constants from "../common/Common_Constants.bs.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Common_OpenInNewButton from "../common/Common_OpenInNewButton.bs.js";
import * as Styles from "@material-ui/core/styles";

function Contact_Content(props) {
  var match = React.useState(function () {
        
      });
  var setMapUrl = match[1];
  var mapUrl = match[0];
  var match$1 = React.useState(function () {
        return false;
      });
  var setIsMapBeingLoaded = match$1[1];
  var isMapBeingLoaded = match$1[0];
  var intl = ReactIntl.useIntl();
  var commonClasses = Common_Style.useStyles();
  var isSmUp = Core.useMediaQuery(Core$Mui.Breakpoint.get(Styles.useTheme(), {
            NAME: "up",
            VAL: "sm"
          }));
  var onClose = function (param) {
    Curry._1(setIsMapBeingLoaded, (function (param) {
            return false;
          }));
    Curry._1(setMapUrl, (function (param) {
            
          }));
  };
  var onClick = function (mapUrl, param) {
    Curry._1(setIsMapBeingLoaded, (function (param) {
            return true;
          }));
    Curry._1(setMapUrl, (function (param) {
            return mapUrl;
          }));
  };
  var onMapLoadingFinished = function (param) {
    Curry._1(setIsMapBeingLoaded, (function (param) {
            return false;
          }));
  };
  return JsxRuntime.jsxs(Core.Grid, {
              children: [
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsxs(Core.Grid, {
                                children: [
                                  isSmUp ? JsxRuntime.jsx(Core.Grid, {
                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.header)),
                                                    variant: "h4"
                                                  })),
                                          className: commonClasses.centeredText,
                                          item: true,
                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                        }) : null,
                                  JsxRuntime.jsx(Core.Grid, {
                                        children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                  children: Caml_option.some(intl.formatMessage(Message.Contact.openingTimes)),
                                                  className: commonClasses.bold
                                                })),
                                        item: true,
                                        xs: Caml_option.some(Grid$Mui.Xs[12])
                                      })
                                ],
                                className: commonClasses.paragraphGap,
                                container: true
                              })),
                      item: true,
                      xs: Caml_option.some(Grid$Mui.Xs[12])
                    }),
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsxs(Core.Grid, {
                                children: [
                                  JsxRuntime.jsx(Core.Grid, {
                                        children: Caml_option.some(JsxRuntime.jsxs(Core.Grid, {
                                                  children: [
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.companyName)),
                                                                    className: commonClasses.bold
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.companyOwner))
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.companyEmail) + " " + Common_Constants.companyEmail)
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        })
                                                  ],
                                                  container: true
                                                })),
                                        item: true,
                                        xs: Caml_option.some(Grid$Mui.Xs[12])
                                      }),
                                  JsxRuntime.jsx(Core.Grid, {
                                        children: Caml_option.some(JsxRuntime.jsxs(Core.Grid, {
                                                  children: [
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.infoContactHeader)),
                                                                    className: commonClasses.bold
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.infoContactPhone) + " " + Common_Constants.infoPhone)
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.infoContactEmail) + " " + Common_Constants.infoEmail)
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        })
                                                  ],
                                                  container: true
                                                })),
                                        item: true,
                                        xs: Caml_option.some(Grid$Mui.Xs[12])
                                      }),
                                  JsxRuntime.jsx(Core.Grid, {
                                        children: Caml_option.some(JsxRuntime.jsxs(Core.Grid, {
                                                  children: [
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.registrationAddressHeader)),
                                                                    className: commonClasses.bold
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Common_OpenInNewButton.make, {
                                                                    label: Message.Contact.registrationAddress,
                                                                    onClick: (function (param) {
                                                                        return onClick(Common_Constants.registrationAddressMapUrl, param);
                                                                      })
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.registrationAddressConnection))
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.registrationAddressParkingLabel))
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.registrationAddressParking))
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Common_OpenInNewButton.make, {
                                                                    label: Message.Contact.registrationAddressPaidParking1,
                                                                    onClick: (function (param) {
                                                                        return onClick(Common_Constants.registrationAddressPaidParking1, param);
                                                                      })
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Common_OpenInNewButton.make, {
                                                                    label: Message.Contact.registrationAddressPaidParking2,
                                                                    onClick: (function (param) {
                                                                        return onClick(Common_Constants.registrationAddressPaidParking2, param);
                                                                      })
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        })
                                                  ],
                                                  container: true
                                                })),
                                        item: true,
                                        xs: Caml_option.some(Grid$Mui.Xs[12])
                                      }),
                                  JsxRuntime.jsx(Core.Grid, {
                                        children: Caml_option.some(JsxRuntime.jsxs(Core.Grid, {
                                                  children: [
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                    children: Caml_option.some(intl.formatMessage(Message.Contact.facturationAddressLabel)),
                                                                    className: commonClasses.bold
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        }),
                                                    JsxRuntime.jsx(Core.Grid, {
                                                          children: Caml_option.some(JsxRuntime.jsx(Common_OpenInNewButton.make, {
                                                                    label: Message.Contact.facturationAddress,
                                                                    onClick: (function (param) {
                                                                        return onClick(Common_Constants.facturationAddress, param);
                                                                      })
                                                                  })),
                                                          item: true,
                                                          xs: Caml_option.some(Grid$Mui.Xs[12])
                                                        })
                                                  ],
                                                  container: true
                                                })),
                                        item: true,
                                        xs: Caml_option.some(Grid$Mui.Xs[12])
                                      }),
                                  JsxRuntime.jsx(Core.Grid, {
                                        children: Caml_option.some(JsxRuntime.jsx(Core.Grid, {
                                                  children: Caml_option.some(JsxRuntime.jsx(Core.Grid, {
                                                            children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                      children: Caml_option.some(intl.formatMessage(Message.Contact.idNumber))
                                                                    })),
                                                            item: true,
                                                            xs: Caml_option.some(Grid$Mui.Xs[12])
                                                          })),
                                                  container: true
                                                })),
                                        item: true,
                                        xs: Caml_option.some(Grid$Mui.Xs[12])
                                      })
                                ],
                                className: commonClasses.paragraphGap,
                                container: true
                              })),
                      className: commonClasses.headerGap,
                      item: true,
                      md: Caml_option.some(Grid$Mui.Md[6]),
                      xs: Caml_option.some(Grid$Mui.Xs[12])
                    }),
                JsxRuntime.jsx(Core.Hidden, {
                      children: Caml_option.some(JsxRuntime.jsx(Core.Grid, {
                                children: Caml_option.some(JsxRuntime.jsx(Contact_Map.make, {
                                          url: mapUrl,
                                          isMapBeingLoaded: isMapBeingLoaded,
                                          onMapLoadingFinished: onMapLoadingFinished
                                        })),
                                className: commonClasses.headerGap,
                                item: true,
                                md: Caml_option.some(Grid$Mui.Md[6])
                              })),
                      mdUp: Belt_Option.isNone(mapUrl),
                      smDown: true
                    }),
                JsxRuntime.jsx(Core.Hidden, {
                      children: Caml_option.some(JsxRuntime.jsx(Common_Dialog.make, {
                                isOpen: Belt_Option.isSome(mapUrl),
                                onClose: onClose,
                                children: JsxRuntime.jsx(Contact_Map.make, {
                                      url: mapUrl,
                                      isMapBeingLoaded: isMapBeingLoaded,
                                      onMapLoadingFinished: onMapLoadingFinished
                                    }),
                                fullScreen: true
                              })),
                      mdUp: true
                    })
              ],
              container: true
            });
}

var Simple;

var make = Contact_Content;

export {
  Simple ,
  make ,
}
/* react Not a pure module */
