// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core$Mui from "rescript-material-ui/src/Core.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/core/styles";

function Contact_Map(Props) {
  var src = Props.url;
  var isSmUp = Core.useMediaQuery(Core$Mui.Breakpoint.get(Styles.useTheme(), {
            NAME: "up",
            VAL: "sm"
          }));
  var isMdUp = Core.useMediaQuery(Core$Mui.Breakpoint.get(Styles.useTheme(), {
            NAME: "up",
            VAL: "md"
          }));
  var tmp = {
    style: {
      border: "none"
    },
    height: isMdUp ? "100%" : (
        isSmUp ? "333px" : "280px"
      ),
    width: "100%"
  };
  if (src !== undefined) {
    tmp.src = Caml_option.valFromOption(src);
  }
  return React.createElement("iframe", tmp);
}

var make = Contact_Map;

export {
  make ,
}
/* react Not a pure module */
