// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Contact_Content from "./Contact_Content.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function Contact_Section(props) {
  return JsxRuntime.jsx(Contact_Content.make, {});
}

var make = Contact_Section;

export {
  make ,
}
/* Contact_Content Not a pure module */
