// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReactIntl from "react-intl";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/styles";
import * as Common_Icon_MailOutline from "../icon/Common_Icon_MailOutline.bs.js";

var useStyles = Styles.makeStyles({
      iconGap: {
        gridColumnGap: "0.5rem"
      }
    });

function Common_Button_WithIcon(props) {
  var intl = ReactIntl.useIntl();
  var classes = useStyles();
  return JsxRuntime.jsx(Core.Button, {
              onClick: props.onClick,
              children: Caml_option.some(JsxRuntime.jsxs(Core.Grid, {
                        alignItems: "center",
                        children: [
                          JsxRuntime.jsx(Common_Icon_MailOutline.make, {}),
                          intl.formatMessage(props.label)
                        ],
                        className: classes.iconGap,
                        container: true
                      })),
              variant: "outlined"
            });
}

var Icon;

var make = Common_Button_WithIcon;

export {
  Icon ,
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
