// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactIntl from "react-intl";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/styles";
import * as Common_Icon_MailOutline from "../icon/Common_Icon_MailOutline.bs.js";

var useStyles = Styles.makeStyles({
      iconGap: {
        gridColumnGap: "0.5rem"
      }
    });

function Common_Button_WithIcon(Props) {
  var label = Props.label;
  var onClick = Props.onClick;
  var intl = ReactIntl.useIntl();
  var classes = useStyles();
  return React.createElement(Core.Button, {
              onClick: onClick,
              children: React.createElement(Core.Grid, {
                    alignItems: "center",
                    children: null,
                    className: classes.iconGap,
                    container: true
                  }, React.createElement(Common_Icon_MailOutline.make, {}), intl.formatMessage(label)),
              variant: "outlined"
            });
}

var Icon;

var make = Common_Button_WithIcon;

export {
  Icon ,
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
