// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/styles";

var useStyles = Styles.makeStyles({
      imageContainer: {
        paddingTop: "30%",
        position: "relative",
        width: "100%"
      },
      image: {
        height: "100%",
        position: "absolute",
        top: "0",
        width: "100%"
      }
    });

function Home_CarouselItem(props) {
  var classes = useStyles();
  return JsxRuntime.jsx(Core.Card, {
              children: Caml_option.some(JsxRuntime.jsx(Core.CardMedia, {
                        className: classes.image,
                        image: props.image
                      })),
              className: classes.imageContainer
            });
}

var make = Home_CarouselItem;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
