// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Message from "../i18n/Message.bs.js";
import * as Grid$Mui from "rescript-material-ui/src/Grid.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Common_Text from "../common/Common_Text.bs.js";
import * as News_Section from "../news/News_Section.bs.js";
import * as Common_Constants from "../common/Common_Constants.bs.js";
import * as Core from "@material-ui/core";
import * as Home_CarouselItem from "./Home_CarouselItem.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/styles";
import ReactMaterialUiCarousel from "react-material-ui-carousel";

var useStyles = Styles.makeStyles({
      verticalGap: {
        gridRowGap: "2rem"
      },
      horizontalGap: {
        paddingRight: "1rem",
        paddingLeft: "1rem"
      }
    });

function Home_Page(props) {
  var classes = useStyles();
  return JsxRuntime.jsxs(Core.Grid, {
              children: [
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsx(ReactMaterialUiCarousel, {
                                autoPlay: true,
                                indicators: false,
                                animation: "slide",
                                children: [
                                  JsxRuntime.jsx(Home_CarouselItem.make, {
                                        image: "/kids/pexels-bess-hamiti-35188.jpg"
                                      }),
                                  JsxRuntime.jsx(Home_CarouselItem.make, {
                                        image: "/kids/pexels-lukas-296301.jpg"
                                      }),
                                  JsxRuntime.jsx(Home_CarouselItem.make, {
                                        image: "/kids/pexels-samer-daboul-1212805.jpg"
                                      }),
                                  JsxRuntime.jsx(Home_CarouselItem.make, {
                                        image: "/kids/pexels-samer-daboul-1815257.jpg"
                                      })
                                ]
                              })),
                      item: true,
                      xs: Caml_option.some(Grid$Mui.Xs[12])
                    }),
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsx(Common_Text.make, {
                                header: Message.Home.firstParagraphHeader,
                                paragraphs: {
                                  hd: Message.Home.firstParagraph,
                                  tl: /* [] */0
                                },
                                centerAll: true
                              })),
                      className: classes.horizontalGap,
                      item: true,
                      md: Caml_option.some(Grid$Mui.Md[4]),
                      sm: Caml_option.some(Grid$Mui.Sm[6]),
                      xs: Caml_option.some(Grid$Mui.Xs[12])
                    }),
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsx(Common_Text.make, {
                                header: Message.Home.secondParagraphHeader,
                                paragraphs: {
                                  hd: Message.Home.secondParagraph,
                                  tl: /* [] */0
                                },
                                centerAll: true
                              })),
                      className: classes.horizontalGap,
                      item: true,
                      md: Caml_option.some(Grid$Mui.Md[4]),
                      sm: Caml_option.some(Grid$Mui.Sm[6]),
                      xs: Caml_option.some(Grid$Mui.Xs[12])
                    }),
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsx(Common_Text.make, {
                                header: Message.Home.thirdParagraphHeader,
                                paragraphs: {
                                  hd: Message.Home.thirdParagraph,
                                  tl: /* [] */0
                                },
                                centerAll: true
                              })),
                      className: classes.horizontalGap,
                      item: true,
                      md: Caml_option.some(Grid$Mui.Md[4]),
                      sm: Caml_option.some(Grid$Mui.Sm[6]),
                      xs: Caml_option.some(Grid$Mui.Xs[12])
                    }),
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsx("hr", {})),
                      item: true,
                      xs: Caml_option.some(Grid$Mui.Xs[12]),
                      id: Common_Constants.SectionAnchor.latestNews
                    }),
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsx(News_Section.make, {})),
                      item: true,
                      xs: Caml_option.some(Grid$Mui.Xs[12])
                    })
              ],
              className: classes.verticalGap,
              container: true
            });
}

var CarouselItem;

var make = Home_Page;

export {
  CarouselItem ,
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
