// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/styles";

var useStyles = Styles.makeStyles({
      imageContainer: {
        paddingTop: "30%",
        position: "relative",
        width: "100%"
      },
      image: {
        height: "100%",
        position: "absolute",
        top: "0",
        width: "100%"
      }
    });

function Home_CarouselItem(Props) {
  var image = Props.image;
  var classes = useStyles();
  return React.createElement(Core.Card, {
              children: React.createElement(Core.CardMedia, {
                    className: classes.image,
                    image: image
                  }),
              className: classes.imageContainer
            });
}

var make = Home_CarouselItem;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
