// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Home_CarouselItem from "./Home_CarouselItem.bs.js";
import ReactMaterialUiCarousel from "react-material-ui-carousel";

function Home_Page(Props) {
  return React.createElement(ReactMaterialUiCarousel, {
              autoPlay: false,
              indicators: false,
              animation: "slide",
              children: [
                React.createElement(Home_CarouselItem.make, {
                      image: "/kids/pexels-bess-hamiti-35188.jpg"
                    }),
                React.createElement(Home_CarouselItem.make, {
                      image: "/kids/pexels-lukas-296301.jpg"
                    }),
                React.createElement(Home_CarouselItem.make, {
                      image: "/kids/pexels-samer-daboul-1212805.jpg"
                    }),
                React.createElement(Home_CarouselItem.make, {
                      image: "/kids/pexels-samer-daboul-1815257.jpg"
                    })
              ]
            });
}

var CarouselItem;

var make = Home_Page;

export {
  CarouselItem ,
  make ,
}
/* react Not a pure module */
