// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Message from "../i18n/Message.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";

function toLabel(page) {
  switch (page) {
    case /* LatestNews */0 :
        return Message.Menu.news;
    case /* AboutUs */1 :
        return Message.Menu.aboutUs;
    case /* References */2 :
        return Message.Menu.references;
    case /* Contact */3 :
        return Message.Menu.contact;
    
  }
}

function Home_Section(props) {
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsx("hr", {})),
                      item: true,
                      id: props.anchor
                    }),
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(props.children),
                      item: true
                    })
              ]
            });
}

var make = Home_Section;

export {
  toLabel ,
  make ,
}
/* @material-ui/core Not a pure module */
