// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Message from "../i18n/Message.bs.js";

function toLabel(page) {
  switch (page) {
    case /* LatestNews */0 :
        return Message.Menu.news;
    case /* AboutUs */1 :
        return Message.Menu.aboutUs;
    case /* References */2 :
        return Message.Menu.references;
    case /* Contact */3 :
        return Message.Menu.contact;
    
  }
}

export {
  toLabel ,
}
/* No side effect */
