// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Message from "../i18n/Message.bs.js";
import * as Core from "@material-ui/core";
import * as Common_Button_WithIcon from "../common/button/Common_Button_WithIcon.bs.js";

function TopHeader(Props) {
  return React.createElement(Core.Grid, {
              alignItems: "center",
              children: React.createElement(Core.Grid, {
                    children: React.createElement(Common_Button_WithIcon.make, {
                          label: Message.Menu.emailUs
                        }),
                    item: true
                  }),
              container: true,
              direction: "column"
            });
}

var make = TopHeader;

export {
  make ,
}
/* react Not a pure module */
