// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Message from "../i18n/Message.bs.js";
import * as ReactIntl from "react-intl";
import * as App_Actions from "../App_Actions.bs.js";
import * as App_Context from "../App_Context.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Common_Style from "../common/Common_Style.bs.js";
import * as Common_Constants from "../common/Common_Constants.bs.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/styles";
import * as TopHeader_Container from "./TopHeader_Container.bs.js";
import * as Common_Button_WithIcon from "../common/button/Common_Button_WithIcon.bs.js";

var useStyles = Styles.makeStyles({
      logoContainer: {
        width: "26%"
      },
      logo: {
        height: "10vw"
      }
    });

function TopHeader(props) {
  var intl = ReactIntl.useIntl();
  var classes = useStyles();
  var commonClasses = Common_Style.useStyles();
  var match = React.useContext(App_Context.Context.t);
  var dispatch = match[1];
  var onEmailUs = function (e) {
    window.location.href = "mailto:" + Common_Constants.infoEmail + "";
    e.preventDefault();
  };
  var onLogoClick = function (param) {
    App_Actions.goToPage(/* Home */0, dispatch);
  };
  var onRegisterClick = function (param) {
    App_Actions.goToPage(/* Registrations */2, dispatch);
  };
  return JsxRuntime.jsxs(TopHeader_Container.make, {
              children: [
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsx(Common_Button_WithIcon.make, {
                                label: Message.Menu.emailUs,
                                onClick: onEmailUs
                              })),
                      item: true
                    }),
                JsxRuntime.jsx(Core.Hidden, {
                      children: Caml_option.some(JsxRuntime.jsx(Core.Grid, {
                                children: Caml_option.some(JsxRuntime.jsx(Core.ButtonBase, {
                                          children: Caml_option.some(JsxRuntime.jsx("img", {
                                                    className: classes.logo,
                                                    src: "/poppy_logo.jpg"
                                                  })),
                                          className: commonClasses.fullWidth,
                                          onClick: onLogoClick
                                        })),
                                className: classes.logoContainer,
                                item: true
                              })),
                      smDown: true
                    }),
                JsxRuntime.jsx(Core.Grid, {
                      children: Caml_option.some(JsxRuntime.jsx(Core.Button, {
                                onClick: onRegisterClick,
                                children: Caml_option.some(intl.formatMessage(Message.Menu.registrations)),
                                color: "secondary",
                                variant: "contained"
                              })),
                      item: true
                    })
              ]
            });
}

var Container;

var make = TopHeader;

export {
  Container ,
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
