// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/styles";

var useStyles = Styles.makeStyles({
      xsItemGap: {
        gridRowGap: "1rem"
      }
    });

function TopHeader_Container(Props) {
  var children = Props.children;
  var classes = useStyles();
  return React.createElement(React.Fragment, undefined, React.createElement(Core.Hidden, {
                  children: React.createElement(Core.Grid, {
                        children: children,
                        container: true,
                        direction: "row",
                        justify: "space-between",
                        wrap: "nowrap"
                      }),
                  xsDown: true
                }), React.createElement(Core.Hidden, {
                  children: React.createElement(Core.Grid, {
                        alignItems: "center",
                        children: children,
                        className: classes.xsItemGap,
                        container: true,
                        direction: "column"
                      }),
                  smUp: true
                }));
}

var make = TopHeader_Container;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
