// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/styles";

var useStyles = Styles.makeStyles({
      xsItemGap: {
        gridRowGap: "1rem"
      }
    });

function TopHeader_Container(props) {
  var children = props.children;
  var classes = useStyles();
  return JsxRuntime.jsxs(JsxRuntime.Fragment, {
              children: [
                JsxRuntime.jsx(Core.Hidden, {
                      children: Caml_option.some(JsxRuntime.jsx(Core.Grid, {
                                children: Caml_option.some(children),
                                container: true,
                                direction: "row",
                                justify: "space-between",
                                wrap: "nowrap"
                              })),
                      xsDown: true
                    }),
                JsxRuntime.jsx(Core.Hidden, {
                      children: Caml_option.some(JsxRuntime.jsx(Core.Grid, {
                                alignItems: "center",
                                children: Caml_option.some(children),
                                className: classes.xsItemGap,
                                container: true,
                                direction: "column"
                              })),
                      smUp: true
                    })
              ]
            });
}

var make = TopHeader_Container;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
