// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as App_Page from "../App_Page.bs.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as ReactIntl from "react-intl";
import * as App_Actions from "../App_Actions.bs.js";
import * as App_Context from "../App_Context.bs.js";
import * as Core from "@material-ui/core";

function TopMenu_Tabs(Props) {
  var intl = ReactIntl.useIntl();
  var match = React.useContext(App_Context.Context.t);
  var dispatch = match[1];
  return React.createElement(Core.Tabs, {
              children: Belt_List.toArray(Belt_List.map(App_Page.menuItems(undefined), (function (page) {
                          return React.createElement(Core.Tab, {
                                      label: intl.formatMessage(App_Page.toLabel(page)),
                                      onClick: (function (param) {
                                          App_Actions.goToPage(page, dispatch);
                                        }),
                                      value: page
                                    });
                        }))),
              value: match[0].activeMenuItem,
              variant: "fullWidth"
            });
}

var make = TopMenu_Tabs;

export {
  make ,
}
/* react Not a pure module */
