// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core$Mui from "rescript-material-ui/src/Core.bs.js";
import * as App_Context from "../App_Context.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as TopMenu_Tab from "./TopMenu_Tab.bs.js";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/core/styles";

function TopMenu(Props) {
  var isMdUp = Core.useMediaQuery(Core$Mui.Breakpoint.get(Styles.useTheme(), {
            NAME: "up",
            VAL: "md"
          }));
  var match = React.useContext(App_Context.Context.t);
  var activeMenuItem = match[0].activeMenuItem;
  var tmp = {
    children: React.createElement(Core.Grid, {
          children: React.createElement(Core.Grid, {
                children: React.createElement(Core.Tabs, {
                      children: null,
                      value: activeMenuItem !== undefined ? activeMenuItem : false
                    }, React.createElement(TopMenu_Tab.make, {
                          page: /* AboutUs */0
                        }), React.createElement(TopMenu_Tab.make, {
                          page: /* Registrations */1
                        }), React.createElement(TopMenu_Tab.make, {
                          page: /* References */2
                        }), React.createElement(TopMenu_Tab.make, {
                          page: /* Contact */3
                        })),
                item: true
              }),
          container: true
        })
  };
  var tmp$1 = isMdUp ? "dense" : undefined;
  if (tmp$1 !== undefined) {
    tmp.variant = Caml_option.valFromOption(tmp$1);
  }
  return React.createElement(Core.AppBar, {
              children: React.createElement(Core.Toolbar, tmp),
              position: "sticky"
            });
}

var Tab;

var make = TopMenu;

export {
  Tab ,
  make ,
}
/* react Not a pure module */
