// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Common_Constants from "../common/Common_Constants.bs.js";

function menuItems(isLatestNewsRead) {
  if (isLatestNewsRead) {
    return {
            hd: /* LatestNews */0,
            tl: {
              hd: /* AboutUs */1,
              tl: {
                hd: /* References */2,
                tl: {
                  hd: /* Contact */3,
                  tl: /* [] */0
                }
              }
            }
          };
  } else {
    return {
            hd: /* AboutUs */1,
            tl: {
              hd: /* References */2,
              tl: {
                hd: /* Contact */3,
                tl: /* [] */0
              }
            }
          };
  }
}

function scrollToSection(sectionAnchor) {
  var anchor = document.querySelector("#" + sectionAnchor + "");
  Belt_Option.forEach((anchor == null) ? undefined : Caml_option.some(anchor), (function (anchor) {
          anchor.scrollIntoView({
                behavior: "smooth",
                block: "start",
                inline: "start"
              });
        }));
}

function onClick(onSuccessOpt, homeSection) {
  var onSuccess = onSuccessOpt !== undefined ? onSuccessOpt : (function (param) {
        
      });
  switch (homeSection) {
    case /* LatestNews */0 :
        scrollToSection(Common_Constants.SectionAnchor.latestNews);
        break;
    case /* AboutUs */1 :
        console.log("Scrolling to about us");
        break;
    case /* References */2 :
        console.log("Scrolling to references");
        break;
    case /* Contact */3 :
        console.log("Scrolling to contact");
        break;
    
  }
  Curry._1(onSuccess, undefined);
}

export {
  menuItems ,
  scrollToSection ,
  onClick ,
}
/* No side effect */
