// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Message from "../i18n/Message.bs.js";
import * as News_Idb from "../news/News_Idb.bs.js";
import * as ReactIntl from "react-intl";
import * as App_Actions from "../App_Actions.bs.js";
import * as App_Context from "../App_Context.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as TopMenu_Tabs from "./TopMenu_Tabs.bs.js";
import * as TopMenu_Drawer from "./TopMenu_Drawer.bs.js";
import * as Common_Icon_Menu from "../common/icon/Common_Icon_Menu.bs.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";

function TopMenu(props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsLatestNewsRead = match[1];
  var isLatestNewsRead = match[0];
  var match$1 = React.useState(function () {
        return false;
      });
  var setDrawerOpen = match$1[1];
  var intl = ReactIntl.useIntl();
  var match$2 = React.useContext(App_Context.Context.t);
  var dispatch = match$2[1];
  React.useEffect((function () {
          News_Idb.isLatestNewsRead(undefined).then(function (isLatestNewsRead) {
                Curry._1(setIsLatestNewsRead, (function (param) {
                        return isLatestNewsRead;
                      }));
              });
        }), [match$2[0].latestNewsClosed]);
  var onAppNameClick = function (param) {
    App_Actions.goToPage(/* Home */0, dispatch);
  };
  return JsxRuntime.jsxs(Core.AppBar, {
              children: [
                JsxRuntime.jsx(TopMenu_Drawer.make, {
                      drawerOpen: match$1[0],
                      onClose: (function (param) {
                          Curry._1(setDrawerOpen, (function (param) {
                                  return false;
                                }));
                        }),
                      isLatestNewsRead: isLatestNewsRead
                    }),
                JsxRuntime.jsx(Core.Hidden, {
                      children: Caml_option.some(JsxRuntime.jsx(TopMenu_Tabs.make, {
                                isLatestNewsRead: isLatestNewsRead
                              })),
                      smDown: true
                    }),
                JsxRuntime.jsx(Core.Hidden, {
                      children: Caml_option.some(JsxRuntime.jsx(Core.Toolbar, {
                                children: Caml_option.some(JsxRuntime.jsxs(Core.Grid, {
                                          alignItems: "center",
                                          children: [
                                            JsxRuntime.jsx(Core.Grid, {
                                                  children: Caml_option.some(JsxRuntime.jsx(Core.ButtonBase, {
                                                            children: Caml_option.some(JsxRuntime.jsx(Core.Typography, {
                                                                      children: Caml_option.some(intl.formatMessage(Message.appName)),
                                                                      variant: "h5"
                                                                    })),
                                                            onClick: onAppNameClick
                                                          })),
                                                  item: true
                                                }),
                                            JsxRuntime.jsx(Core.Grid, {
                                                  children: Caml_option.some(JsxRuntime.jsx(Core.IconButton, {
                                                            onClick: (function (param) {
                                                                Curry._1(setDrawerOpen, (function (param) {
                                                                        return true;
                                                                      }));
                                                              }),
                                                            children: Caml_option.some(JsxRuntime.jsx(Common_Icon_Menu.make, {}))
                                                          })),
                                                  item: true
                                                })
                                          ],
                                          container: true,
                                          justify: "space-between"
                                        }))
                              })),
                      mdUp: true
                    })
              ],
              position: "static"
            });
}

var Drawer;

var Item;

var Tabs;

var make = TopMenu;

export {
  Drawer ,
  Item ,
  Tabs ,
  make ,
}
/* react Not a pure module */
