// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as App_Page from "../App_Page.bs.js";
import * as ReactIntl from "react-intl";
import * as App_Context from "../App_Context.bs.js";
import * as Core from "@material-ui/core";

function TopMenu_Tab(Props) {
  var page = Props.page;
  var intl = ReactIntl.useIntl();
  var match = React.useContext(App_Context.Context.t);
  var dispatch = match[1];
  return React.createElement(Core.Tab, {
              label: intl.formatMessage(App_Page.toLabel(page)),
              onClick: (function (param) {
                  Curry._1(dispatch, /* StoreActiveMenuItem */{
                        _0: page
                      });
                }),
              value: page
            });
}

var make = TopMenu_Tab;

export {
  make ,
}
/* react Not a pure module */
