// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Message from "../i18n/Message.bs.js";
import * as Common_Text from "../common/Common_Text.bs.js";

function AboutUs_Page(Props) {
  return React.createElement(Common_Text.make, {
              header: Message.AboutUs.header,
              paragraphs: {
                hd: Message.AboutUs.paragraph1,
                tl: {
                  hd: Message.AboutUs.paragraph2,
                  tl: {
                    hd: Message.AboutUs.paragraph3,
                    tl: {
                      hd: Message.AboutUs.paragraph4,
                      tl: /* [] */0
                    }
                  }
                }
              }
            });
}

var make = AboutUs_Page;

export {
  make ,
}
/* react Not a pure module */
