// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "@material-ui/core/styles";

function getColors(prefersDarkTheme) {
  return {
          primary: prefersDarkTheme ? "#303030" : "#fafafa"
        };
}

function theme(prefersDarkTheme) {
  var colors = getColors(prefersDarkTheme);
  return Styles.createTheme({
              palette: {
                error: {
                  main: "#de0522"
                },
                info: {
                  main: "#ffe401"
                },
                primary: {
                  main: colors.primary
                },
                secondary: {
                  main: "#009ada"
                },
                success: {
                  main: "#68a130"
                },
                type: prefersDarkTheme ? "dark" : "light",
                warning: {
                  main: "#f1a300"
                }
              }
            });
}

export {
  getColors ,
  theme ,
}
/* @material-ui/core/styles Not a pure module */
