// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Menu from "@material-ui/icons/Menu";

var Menu$1 = {};

function App_Icon_Menu(Props) {
  var color = Props.color;
  var fontSize = Props.fontSize;
  var className = Props.className;
  var tmp = {};
  if (color !== undefined) {
    tmp.color = color;
  }
  if (fontSize !== undefined) {
    tmp.fontSize = fontSize;
  }
  if (className !== undefined) {
    tmp.className = className;
  }
  return React.createElement(Menu, tmp);
}

var make = App_Icon_Menu;

export {
  Menu$1 as Menu,
  make ,
}
/* react Not a pure module */
