// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Message from "../i18n/Message.bs.js";
import * as Grid$Mui from "rescript-material-ui/src/Grid.bs.js";
import * as ReactIntl from "react-intl";
import * as App_Context from "../App_Context.bs.js";
import * as Common_Text from "../common/Common_Text.bs.js";
import * as Common_Style from "../common/Common_Style.bs.js";
import * as Core from "@material-ui/core";

function References_Page(Props) {
  var intl = ReactIntl.useIntl();
  var classes = Common_Style.useStyles();
  var match = React.useContext(App_Context.Context.t);
  var dispatch = match[1];
  var activeMenuItem = match[0].activeMenuItem;
  React.useEffect((function () {
          if (activeMenuItem !== /* References */2) {
            Curry._1(dispatch, /* StoreActiveMenuItem */{
                  _0: /* References */2
                });
          }
          
        }), [activeMenuItem]);
  return React.createElement(Core.Grid, {
              children: null,
              container: true
            }, React.createElement(Core.Grid, {
                  children: React.createElement(Common_Text.make, {
                        header: Message.References.header,
                        paragraphs: {
                          hd: Message.References.paragraph1,
                          tl: /* [] */0
                        }
                      }),
                  item: true
                }), React.createElement(Core.Grid, {
                  children: React.createElement(Core.Typography, {
                        children: intl.formatMessage(Message.References.section2Header),
                        variant: "h5"
                      }),
                  className: classes.headerGap,
                  item: true,
                  xs: Grid$Mui.Xs[12]
                }), React.createElement(Core.Grid, {
                  children: React.createElement(Core.Grid, {
                        children: null,
                        className: classes.paragraphGap,
                        container: true
                      }, React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: intl.formatMessage(Message.References.tvAndFilmHeader),
                                  variant: "h6"
                                }),
                            item: true,
                            xs: Grid$Mui.Xs[12]
                          }), React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: intl.formatMessage(Message.References.tvAndFilmList)
                                }),
                            item: true,
                            xs: Grid$Mui.Xs[12]
                          }), React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: intl.formatMessage(Message.References.adsHeader),
                                  variant: "h6"
                                }),
                            item: true,
                            xs: Grid$Mui.Xs[12]
                          }), React.createElement(Core.Grid, {
                            children: React.createElement(Core.Typography, {
                                  children: intl.formatMessage(Message.References.adsList)
                                }),
                            item: true,
                            xs: Grid$Mui.Xs[12]
                          })),
                  className: classes.headerGap,
                  item: true
                }));
}

var make = References_Page;

export {
  make ,
}
/* react Not a pure module */
