// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";

function Registrations_Page(Props) {
  return React.createElement(Core.Grid, {});
}

var make = Registrations_Page;

export {
  make ,
}
/* react Not a pure module */
