// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Message from "../i18n/Message.bs.js";
import * as Core$Mui from "rescript-material-ui/src/Core.bs.js";
import * as App_Context from "../App_Context.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Common_Text from "../common/Common_Text.bs.js";
import * as Common_Style from "../common/Common_Style.bs.js";
import * as News_Message from "../news/News_Message.bs.js";
import * as Core from "@material-ui/core";
import * as Common_Icon_Close from "../common/icon/Common_Icon_Close.bs.js";
import * as Common_OpenInNewButton from "../common/Common_OpenInNewButton.bs.js";
import * as Styles from "@material-ui/core/styles";

function Registrations_Page(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setDialogOpened = match[1];
  var commonClasses = Common_Style.useStyles();
  var match$1 = React.useContext(App_Context.Context.t);
  var dispatch = match$1[1];
  var activeMenuItem = match$1[0].activeMenuItem;
  var isSmUp = Core.useMediaQuery(Core$Mui.Breakpoint.get(Styles.useTheme(), {
            NAME: "up",
            VAL: "sm"
          }));
  React.useEffect((function () {
          if (activeMenuItem !== /* Registrations */1) {
            Curry._1(dispatch, /* StoreActiveMenuItem */{
                  _0: /* Registrations */1
                });
          }
          
        }), [activeMenuItem]);
  var onOpenClick = function (param) {
    Curry._1(setDialogOpened, (function (param) {
            return true;
          }));
  };
  var onCloseClick = function (param) {
    Curry._1(setDialogOpened, (function (param) {
            return false;
          }));
  };
  var tmp = {
    afterHeader: React.createElement(Common_OpenInNewButton.make, {
          label: Message.Registrations.nextRegistrations,
          onClick: onOpenClick
        }),
    paragraphs: {
      hd: Message.Registrations.paragraph1,
      tl: {
        hd: Message.Registrations.paragraph2,
        tl: {
          hd: Message.Registrations.paragraph3,
          tl: {
            hd: Message.Registrations.paragraph4,
            tl: /* [] */0
          }
        }
      }
    }
  };
  var tmp$1 = isSmUp ? Message.Registrations.header : undefined;
  if (tmp$1 !== undefined) {
    tmp.header = Caml_option.valFromOption(tmp$1);
  }
  return React.createElement(React.Fragment, undefined, React.createElement(Core.Dialog, {
                  children: null,
                  fullScreen: !isSmUp,
                  onClose: (function (param) {
                      return onCloseClick;
                    }),
                  open: match[0]
                }, React.createElement(Core.DialogTitle, {
                      children: React.createElement(Core.Grid, {
                            alignItems: "center",
                            children: null,
                            container: true,
                            justify: "space-between"
                          }, React.createElement(Core.Grid, {
                                children: React.createElement(News_Message.$$Date.make, {
                                      variant: "h4"
                                    }),
                                item: true
                              }), React.createElement(Core.Grid, {
                                children: React.createElement(Core.IconButton, {
                                      onClick: onCloseClick,
                                      children: React.createElement(Common_Icon_Close.make, {})
                                    }),
                                item: true
                              }))
                    }), React.createElement(Core.DialogContent, {
                      children: React.createElement(Core.DialogContentText, {
                            children: React.createElement(Core.Grid, {
                                  children: React.createElement(Core.Grid, {
                                        children: null,
                                        item: true
                                      }, React.createElement(News_Message.Title.make, {
                                            variant: "h5"
                                          }), React.createElement(News_Message.Content.make, {
                                            className: commonClasses.marginTopSm
                                          })),
                                  container: true
                                })
                          })
                    })), React.createElement(Common_Text.make, tmp));
}

var make = Registrations_Page;

export {
  make ,
}
/* react Not a pure module */
