// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Message from "../i18n/Message.bs.js";
import * as App_Context from "../App_Context.bs.js";
import * as Common_Text from "../common/Common_Text.bs.js";

function Registrations_Page(Props) {
  var match = React.useContext(App_Context.Context.t);
  var dispatch = match[1];
  var activeMenuItem = match[0].activeMenuItem;
  React.useEffect((function () {
          if (activeMenuItem !== /* Registrations */1) {
            Curry._1(dispatch, /* StoreActiveMenuItem */{
                  _0: /* Registrations */1
                });
          }
          
        }), [activeMenuItem]);
  return React.createElement(Common_Text.make, {
              header: Message.Registrations.header,
              paragraphs: {
                hd: Message.Registrations.paragraph1,
                tl: {
                  hd: Message.Registrations.paragraph2,
                  tl: {
                    hd: Message.Registrations.paragraph3,
                    tl: {
                      hd: Message.Registrations.paragraph4,
                      tl: /* [] */0
                    }
                  }
                }
              }
            });
}

var make = Registrations_Page;

export {
  make ,
}
/* react Not a pure module */
