// Generated by ReScript, PLEASE EDIT WITH CARE

import * as IdbKeyval from "idb-keyval";

function createStore(name) {
  return IdbKeyval.createStore("" + name + "-db", "" + name + "-store");
}

var store = createStore("poppy");

export {
  createStore ,
  store ,
}
/* store Not a pure module */
