// Generated by ReScript, PLEASE EDIT WITH CARE


function make(disableHysteresis, target, threshold, param) {
  return {
          disableHysteresis: disableHysteresis,
          target: target,
          threshold: threshold
        };
}

var Options = {
  make: make
};

export {
  Options ,
}
/* No side effect */
