// Generated by ReScript, PLEASE EDIT WITH CARE


var latestNews_date = new Date("2021-06-16");

var latestNews_content = {
  hd: /* Filled */{
    _0: {
      emphasis: /* Large */2,
      value: "Registrace nových dětí a přefocení aktuálně neprobíhá."
    }
  },
  tl: {
    hd: /* Filled */{
      _0: {
        emphasis: /* Large */2,
        value: "Nové termíny na podzim vypíšeme zde, můžete nám dát vědět, že máte zájem a informace Vám zašleme."
      }
    },
    tl: {
      hd: /* Filled */{
        _0: {
          emphasis: /* Bold */1,
          value: "info@poppycasting.cz / 730 826 158 - volejte ve všední dny mezi 9-18h"
        }
      },
      tl: {
        hd: /* Empty */0,
        tl: {
          hd: /* Filled */{
            _0: {
              emphasis: /* Bold */1,
              value: "Zájem o novou registraci:"
            }
          },
          tl: {
            hd: /* Filled */{
              _0: {
                emphasis: /* Bold */1,
                value: "Kontaktujte nás a uveďte prosím vždy: věk dítěte, město bydliště, Váš mail a telefonní číslo."
              }
            },
            tl: {
              hd: /* Filled */{
                _0: {
                  emphasis: /* Bold */1,
                  value: "Registrujeme pouze osobně."
                }
              },
              tl: {
                hd: /* Filled */{
                  _0: {
                    emphasis: /* Bold */1,
                    value: "Registrujeme děti ve věku: 6 měs - 18 měs a poté až od 4.narozenin do 15 let"
                  }
                },
                tl: {
                  hd: /* Filled */{
                    _0: {
                      emphasis: /* Bold */1,
                      value: "Děti ve věku od 18 měs do 4.narozenin aktuálně neregistrujeme"
                    }
                  },
                  tl: {
                    hd: /* Filled */{
                      _0: {
                        emphasis: /* Normal */0,
                        value: "kromě dětí neevropského vzhledu a jednovaječných dvojčat."
                      }
                    },
                    tl: {
                      hd: /* Filled */{
                        _0: {
                          emphasis: /* Normal */0,
                          value: "MIMO STANOVENÉ TERMÍNY nás v atelieru NEZASTIHNETE, online registrace neprovádíme"
                        }
                      },
                      tl: {
                        hd: /* Filled */{
                          _0: {
                            emphasis: /* Normal */0,
                            value: "a není možné se registrovat jindy než ve vypsané dny."
                          }
                        },
                        tl: {
                          hd: /* Filled */{
                            _0: {
                              emphasis: /* Normal */0,
                              value: "Dítě se v daném termínu dostaví OSOBNĚ se zákonným zástupcem"
                            }
                          },
                          tl: {
                            hd: /* Filled */{
                              _0: {
                                emphasis: /* Normal */0,
                                value: "Česky hovořící děti bez cizího přízvuku nebo rodilí mluvčí AJ."
                              }
                            },
                            tl: /* [] */0
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};

var latestNews = {
  date: latestNews_date,
  content: latestNews_content
};

export {
  latestNews ,
}
/* latestNews Not a pure module */
