// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";

function News_Dialog(Props) {
  return React.createElement(Core.Dialog, {
              open: true
            });
}

var make = News_Dialog;

export {
  make ,
}
/* react Not a pure module */
