// Generated by ReScript, PLEASE EDIT WITH CARE


function makeLine(emphasisOpt, nextLineEmptyOpt, value) {
  var emphasis = emphasisOpt !== undefined ? emphasisOpt : /* Normal */0;
  var nextLineEmpty = nextLineEmptyOpt !== undefined ? nextLineEmptyOpt : false;
  return {
          emphasis: emphasis,
          value: value,
          nextLineEmpty: nextLineEmpty
        };
}

export {
  makeLine ,
}
/* No side effect */
