// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Message from "../i18n/Message.bs.js";
import * as Common_Text from "../common/Common_Text.bs.js";
import * as News_Message from "./News_Message.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function News_Section(props) {
  return JsxRuntime.jsx(Common_Text.make, {
              header: Message.News.header,
              body: {
                TAG: /* Element */1,
                _0: JsxRuntime.jsx(News_Message.Content.make, {
                      displayDate: false
                    })
              }
            });
}

var make = News_Section;

export {
  make ,
}
/* Common_Text Not a pure module */
