// Generated by ReScript, PLEASE EDIT WITH CARE

import * as News_Message from "./News_Message.bs.js";
import * as JsxRuntime from "react/jsx-runtime";

function News_Section(props) {
  return JsxRuntime.jsx(News_Message.Content.make, {});
}

var make = News_Section;

export {
  make ,
}
/* News_Message Not a pure module */
