// Generated by ReScript, PLEASE EDIT WITH CARE

import * as News_Type from "./News_Type.bs.js";

var latestNews_date = new Date("2022-09-25");

var latestNews_title = {
  hd: "Registrace nových dětí a přefocení aktuálně neprobíhá.",
  tl: {
    hd: "Nové termíny na podzim vypíšeme zde, můžete nám dát vědět, že máte zájem a informace Vám zašleme.",
    tl: /* [] */0
  }
};

var latestNews_content = {
  hd: News_Type.makeLine(/* Bold */1, true, "info@poppycasting.cz / 730 826 158 - volejte ve všední dny mezi 9-18h"),
  tl: {
    hd: News_Type.makeLine(/* Bold */1, undefined, "Zájem o novou registraci:"),
    tl: {
      hd: News_Type.makeLine(/* Bold */1, undefined, "Kontaktujte nás a uveďte prosím vždy: věk dítěte, město bydliště, Váš mail a telefonní číslo."),
      tl: {
        hd: News_Type.makeLine(/* Bold */1, undefined, "Registrujeme pouze osobně."),
        tl: {
          hd: News_Type.makeLine(/* Bold */1, undefined, "Registrujeme děti ve věku: 6 měs - 18 měs a poté až od 4.narozenin do 15 let"),
          tl: {
            hd: News_Type.makeLine(/* Bold */1, undefined, "Děti ve věku od 18 měs do 4.narozenin aktuálně neregistrujeme"),
            tl: {
              hd: News_Type.makeLine(undefined, undefined, "kromě dětí neevropského vzhledu a jednovaječných dvojčat."),
              tl: {
                hd: News_Type.makeLine(undefined, undefined, "MIMO STANOVENÉ TERMÍNY nás v atelieru NEZASTIHNETE, online registrace neprovádíme"),
                tl: {
                  hd: News_Type.makeLine(undefined, undefined, "a není možné se registrovat jindy než ve vypsané dny."),
                  tl: {
                    hd: News_Type.makeLine(undefined, undefined, "Dítě se v daném termínu dostaví OSOBNĚ se zákonným zástupcem"),
                    tl: {
                      hd: News_Type.makeLine(undefined, undefined, "Česky hovořící děti bez cizího přízvuku nebo rodilí mluvčí AJ."),
                      tl: /* [] */0
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};

var latestNews = {
  date: latestNews_date,
  title: latestNews_title,
  content: latestNews_content
};

export {
  latestNews ,
}
/* latestNews Not a pure module */
