// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReDate from "@mobily/rescript-date/src/ReDate.bs.js";
import * as Utils_Idb from "../utils/Utils_Idb.bs.js";
import * as IdbKeyval from "idb-keyval";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

var newsReadKey = "news-read";

function setNewsRead(date) {
  IdbKeyval.set(newsReadKey, date.toISOString(), Utils_Idb.store);
}

function isNewsRead(date) {
  return IdbKeyval.get(newsReadKey, Utils_Idb.store).then(function (lastDate) {
              return Belt_Option.getWithDefault(Belt_Option.map(Belt_Option.map(lastDate, (function (prim) {
                                    return new Date(prim);
                                  })), (function (param) {
                                return ReDate.isEqual(date, param);
                              })), false);
            });
}

export {
  setNewsRead ,
  isNewsRead ,
}
/* Utils_Idb Not a pure module */
