// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ReDate from "@mobily/rescript-date/src/ReDate.bs.js";
import * as Utils_Idb from "../utils/Utils_Idb.bs.js";
import * as IdbKeyval from "idb-keyval";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as News_Latest from "./News_Latest.bs.js";

var newsReadKey = "news-read";

function setNewsRead(date) {
  IdbKeyval.set(newsReadKey, date.toISOString(), Utils_Idb.store);
}

async function isLatestNewsRead(param) {
  var newDate = News_Latest.latestNews.date;
  var lastDate = await IdbKeyval.get(newsReadKey, Utils_Idb.store);
  return Belt_Option.getWithDefault(Belt_Option.map(Belt_Option.map(lastDate, (function (prim) {
                        return new Date(prim);
                      })), (function (lastDate) {
                    if (ReDate.isAfter(lastDate, newDate)) {
                      return true;
                    } else {
                      return ReDate.isEqual(lastDate, newDate);
                    }
                  })), false);
}

export {
  setNewsRead ,
  isLatestNewsRead ,
}
/* Utils_Idb Not a pure module */
