// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core from "@material-ui/core";

function App(Props) {
  return React.createElement(Core.Typography, {
              children: "Hello world"
            });
}

var Theme;

var make = App;

export {
  Theme ,
  make ,
}
/* react Not a pure module */
