// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Scroll from "./common/binding/scroll/Scroll.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as Styles from "@material-ui/styles";
import UseScrollTrigger from "@material-ui/core/useScrollTrigger";

var useStyles = Styles.makeStyles(function (theme) {
      return {
              button: {
                bottom: String(Curry._1(theme.spacing, 2)).concat("px"),
                position: "fixed",
                right: String(Curry._1(theme.spacing, 2)).concat("px")
              }
            };
    });

function App_ScrollToTop(Props) {
  var children = Props.children;
  var $$in = UseScrollTrigger(Scroll.Options.make(true, undefined, 200, undefined));
  var classes = useStyles();
  var onClick = function (param) {
    var anchor = document.querySelector("#back-to-top-anchor");
    Belt_Option.forEach((anchor == null) ? undefined : Caml_option.some(anchor), (function (anchor) {
            anchor.scrollIntoView({
                  behavior: "smooth",
                  block: "center",
                  inline: "nearest"
                });
          }));
  };
  return React.createElement(Core.Zoom, {
              children: React.createElement(Core.ButtonBase, {
                    children: children,
                    className: classes.button,
                    onClick: onClick
                  }),
              in: $$in
            });
}

var make = App_ScrollToTop;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
