// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Message from "./i18n/Message.bs.js";

var home = "/";

var registrations = "/registrations";

var RoutePath = {
  home: home,
  registrations: registrations
};

function toRoutePath(page) {
  if (page) {
    return registrations;
  } else {
    return home;
  }
}

function toLabel(page) {
  if (page) {
    return Message.Menu.registrations;
  } else {
    return Message.Menu.home;
  }
}

export {
  RoutePath ,
  toRoutePath ,
  toLabel ,
}
/* No side effect */
