// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home_Page from "./home/Home_Page.bs.js";
import * as News_Page from "./news/News_Page.bs.js";
import * as AboutUs_Page from "./aboutUs/AboutUs_Page.bs.js";
import * as Contact_Page from "./contact/Contact_Page.bs.js";
import * as References_Page from "./references/References_Page.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Registrations_Page from "./registrations/Registrations_Page.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function App_Router(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (!match) {
    return JsxRuntime.jsx(Home_Page.make, {});
  }
  switch (match.hd) {
    case "about-us" :
        if (match.tl) {
          return JsxRuntime.jsx(Home_Page.make, {});
        } else {
          return JsxRuntime.jsx(AboutUs_Page.make, {});
        }
    case "contact" :
        if (match.tl) {
          return JsxRuntime.jsx(Home_Page.make, {});
        } else {
          return JsxRuntime.jsx(Contact_Page.make, {});
        }
    case "news" :
        if (match.tl) {
          return JsxRuntime.jsx(Home_Page.make, {});
        } else {
          return JsxRuntime.jsx(News_Page.make, {});
        }
    case "references" :
        if (match.tl) {
          return JsxRuntime.jsx(Home_Page.make, {});
        } else {
          return JsxRuntime.jsx(References_Page.make, {});
        }
    case "registrations" :
        if (match.tl) {
          return JsxRuntime.jsx(Home_Page.make, {});
        } else {
          return JsxRuntime.jsx(Registrations_Page.make, {});
        }
    default:
      return JsxRuntime.jsx(Home_Page.make, {});
  }
}

var make = App_Router;

export {
  make ,
}
/* Home_Page Not a pure module */
