// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Message from "./i18n/Message.bs.js";

var aboutUs = "/about-us";

var registrations = "/registrations";

var references = "/references";

var contact = "/contact";

var RoutePath = {
  home: "/",
  aboutUs: aboutUs,
  registrations: registrations,
  references: references,
  contact: contact
};

function toRoutePath(page) {
  switch (page) {
    case /* AboutUs */0 :
        return aboutUs;
    case /* Registrations */1 :
        return registrations;
    case /* References */2 :
        return references;
    case /* Contact */3 :
        return contact;
    
  }
}

function toLabel(page) {
  switch (page) {
    case /* AboutUs */0 :
        return Message.Menu.aboutUs;
    case /* Registrations */1 :
        return Message.Menu.registrations;
    case /* References */2 :
        return Message.Menu.references;
    case /* Contact */3 :
        return Message.Menu.contact;
    
  }
}

export {
  RoutePath ,
  toRoutePath ,
  toLabel ,
}
/* No side effect */
