// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home_Page from "./home/Home_Page.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Registrations_Page from "./registrations/Registrations_Page.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function App_Router(props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = url.path;
  if (match && match.hd === "registrations" && !match.tl) {
    return JsxRuntime.jsx(Registrations_Page.make, {});
  } else {
    return JsxRuntime.jsx(Home_Page.make, {});
  }
}

var make = App_Router;

export {
  make ,
}
/* Home_Page Not a pure module */
