// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as App_Page from "./App_Page.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function goToPage(page, dispatch) {
  Curry._1(dispatch, /* StoreActiveMenuItem */{
        _0: page
      });
  RescriptReactRouter.push(App_Page.toRoutePath(page));
}

export {
  goToPage ,
}
/* RescriptReactRouter Not a pure module */
