// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.bs.js";
import * as App_Theme from "./theme/App_Theme.bs.js";
import * as App_Context from "./App_Context.bs.js";
import * as IntlProvider from "./i18n/IntlProvider.bs.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/core/styles";

function Root(props) {
  var prefersDarkTheme = Core.useMediaQuery("(prefers-color-scheme: dark)");
  return JsxRuntime.jsx(IntlProvider.make, {
              children: JsxRuntime.jsx(App_Context.Provider.make, {
                    children: JsxRuntime.jsxs(Styles.ThemeProvider, {
                          children: [
                            JsxRuntime.jsx(Core.CssBaseline, {}),
                            JsxRuntime.jsx(App.make, {})
                          ],
                          theme: App_Theme.theme(prefersDarkTheme)
                        })
                  })
            });
}

var make = Root;

export {
  make ,
}
/* App Not a pure module */
