// Generated by ReScript, PLEASE EDIT WITH CARE


var companyEmail = "deti@poppycasting.cz";

var infoEmail = "info@poppycasting.cz";

var bossEmail = "martina@poppycasting.cz";

var infoPhone = "730 826 158";

var registrationAddressMapUrl = "https://frame.mapy.cz/s/fedaboceda";

var registrationAddressPaidParking1 = "https://frame.mapy.cz/s/gatunepako";

var registrationAddressPaidParking2 = "https://frame.mapy.cz/s/jocofemeba";

var facturationAddress = "https://frame.mapy.cz/s/gofosakuga";

export {
  companyEmail ,
  infoEmail ,
  bossEmail ,
  infoPhone ,
  registrationAddressMapUrl ,
  registrationAddressPaidParking1 ,
  registrationAddressPaidParking2 ,
  facturationAddress ,
}
/* No side effect */
