// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "@material-ui/styles";

var headerGap = {
  marginTop: "2rem"
};

var useStyles = Styles.makeStyles({
      headerGap: headerGap,
      paragraphGap: {
        gridRowGap: "1rem"
      },
      bold: {
        fontWeight: "bold"
      }
    });

export {
  headerGap ,
  useStyles ,
}
/* useStyles Not a pure module */
