// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Styles from "@material-ui/styles";

var headerGap = {
  marginTop: "2rem"
};

var useStyles = Styles.makeStyles({
      headerGap: headerGap,
      paragraphGap: {
        gridRowGap: "1rem"
      },
      bold: {
        fontWeight: "bold"
      },
      marginBottomSm: {
        marginBottom: "0.75rem"
      },
      marginBottom: {
        marginBottom: "1rem"
      },
      fullWidth: {
        width: "100%"
      }
    });

export {
  headerGap ,
  useStyles ,
}
/* useStyles Not a pure module */
