let companyEmail = "deti@poppycasting.cz"
let infoEmail = "info@poppycasting.cz"
let infoPhone = "730 826 158"
let registrationAddressMapUrl = "https://frame.mapy.cz/s/fedaboceda"
let registrationAddressPaidParking1 = "https://frame.mapy.cz/s/gatunepako"
let registrationAddressPaidParking2 = "https://frame.mapy.cz/s/jocofemeba"
let facturationAddress = "https://frame.mapy.cz/s/gofosakuga"
