// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as ReactIntl from "react-intl";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/styles";
import * as Common_Icon_OpenInNew from "./icon/Common_Icon_OpenInNew.bs.js";

var useStyles = Styles.makeStyles({
      root: {
        textTransform: "none"
      }
    });

function Common_OpenInNewButton(props) {
  var onClick = props.onClick;
  var intl = ReactIntl.useIntl();
  var classes = useStyles();
  return JsxRuntime.jsx(Core.Button, {
              onClick: (function (param) {
                  Curry._1(onClick, undefined);
                }),
              children: Caml_option.some(intl.formatMessage(props.label)),
              classes: {
                root: classes.root
              },
              endIcon: Caml_option.some(JsxRuntime.jsx(Common_Icon_OpenInNew.make, {})),
              variant: "outlined"
            });
}

var make = Common_OpenInNewButton;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
