// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core from "@material-ui/core";
import * as Common_Icon_Close from "./icon/Common_Icon_Close.bs.js";
import * as JsxRuntime from "react/jsx-runtime";
import * as Styles from "@material-ui/styles";

var useStyles = Styles.makeStyles({
      mapSize: {
        height: "50%",
        width: "100%"
      }
    });

function Common_Dialog(props) {
  var onClose = props.onClose;
  var classes = useStyles();
  return JsxRuntime.jsxs(Core.Dialog, {
              children: [
                JsxRuntime.jsx(Core.DialogTitle, {
                      children: Caml_option.some(JsxRuntime.jsx(Core.Grid, {
                                alignItems: "center",
                                children: Caml_option.some(JsxRuntime.jsx(Core.Grid, {
                                          children: Caml_option.some(JsxRuntime.jsx(Core.IconButton, {
                                                    onClick: (function (param) {
                                                        Curry._1(onClose, undefined);
                                                      }),
                                                    children: Caml_option.some(JsxRuntime.jsx(Common_Icon_Close.make, {}))
                                                  })),
                                          item: true
                                        })),
                                container: true,
                                justify: "flex-end"
                              }))
                    }),
                JsxRuntime.jsx(Core.DialogContent, {
                      children: Caml_option.some(props.children)
                    })
              ],
              classes: Belt_Option.flatMap(props.fixedSize, (function (fixedSize) {
                      if (fixedSize) {
                        return {
                                paper: classes.mapSize
                              };
                      }
                      
                    })),
              fullScreen: props.fullScreen,
              onClose: (function (param, param$1) {
                  Curry._1(onClose, undefined);
                }),
              open: props.isOpen
            });
}

var make = Common_Dialog;

export {
  useStyles ,
  make ,
}
/* useStyles Not a pure module */
