// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Grid$Mui from "rescript-material-ui/src/Grid.bs.js";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as ReactIntl from "react-intl";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Common_Style from "./Common_Style.bs.js";
import * as Core from "@material-ui/core";

function Common_Text(Props) {
  var header = Props.header;
  var paragraphs = Props.paragraphs;
  var intl = ReactIntl.useIntl();
  var classes = Common_Style.useStyles();
  return React.createElement(Core.Grid, {
              children: null,
              className: classes.paragraphGap,
              container: true
            }, Belt_Option.mapWithDefault(header, null, (function (header) {
                    return React.createElement(Core.Grid, {
                                children: React.createElement(Core.Typography, {
                                      children: intl.formatMessage(header),
                                      variant: "h4"
                                    }),
                                item: true,
                                xs: Grid$Mui.Xs[12]
                              });
                  })), Belt_List.toArray(Belt_List.map(paragraphs, (function (paragraph) {
                        return React.createElement(Core.Grid, {
                                    children: React.createElement(Core.Typography, {
                                          children: intl.formatMessage(paragraph)
                                        }),
                                    item: true,
                                    xs: Grid$Mui.Xs[12]
                                  });
                      }))));
}

var make = Common_Text;

export {
  make ,
}
/* react Not a pure module */
